app:
  calculator-url:
    default-url: http://localhost:8080

spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: validate
  datasource:
    url: jdbc:postgresql://localhost:5432/CreditBank
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver


server:
  port: 8081