version: '3.8'
services:

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    volumes:
      - ./data/zookeeper/data:/data
      - ./data/zookeeper/datalog:/datalog
  kafka:
    image: bitnami/kafka:latest
    ports:
      - "9092:9092"  # Внешний порт для INSIDE
    #      - "9093:9093"  # Внешний порт для OUTSIDE
    environment:
      KAFKA_ADVERTISED_LISTENERS: INSIDE://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT
      KAFKA_LISTENERS: INSIDE://0.0.0.0:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE  # Установка inter.broker.listener.name
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'

    depends_on:
      - zookeeper